INSERT INTO equipo (id, nombre, imagen) VALUES ('1', 'BVB Dortmund', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('2', 'Chelsea FC', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('3', 'Real Madrid CF', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('4', 'Manchester United FC', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('5', 'Valencia FC', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('6', 'AS Roma', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('7', 'AC Milán', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('8', 'FC Schalke 04', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('9', 'Galatasaray', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('10', 'FC Bayern Munich', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('11', 'Paris Saint-Germain', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('12', 'Bayer 04 Leverkusen', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('13', 'FC Porto', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('14', 'SL Benfica', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('15', 'Manchester City', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('16', 'Atlético de Madrid', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('17', 'AS Mónaco', '??');
