INSERT INTO equipo (id, nombre, imagen) VALUES ('1', 'Real Madrid CF', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('2', 'Arsenal FC', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('3', 'Paris Saint-Germain', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('4', 'FC Barcelona', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('1', 'Real Madrid CF', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('2', 'FC Barcelona', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('3', 'Club Atlético de Madrid', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('1', 'Real Madrid CF', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('2', 'FC Barcelona', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('3', 'FC Bayern Munich', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('4', 'Juventus', '??');
