--Habría que insertarlos manualmente, ya que los bytes de las imágenes no podemos ponerla como texto.
INSERT INTO equipo (id, nombre, imagen) VALUES ('1', 'BVB Dortmund', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('2', 'Chelsea FC', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('3', 'Real Madrid CF', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('4', 'Manchester United FC', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('5', 'Valencia FC', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('6', 'AS Roma', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('7', 'AC Milán', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('8', 'FC Schalke 04', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('9', 'Galatasaray', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('10', 'FC Bayern Munich', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('11', 'Paris Saint-Germain', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('12', 'Bayer 04 Leverkusen', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('13', 'FC Porto', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('14', 'SL Benfica', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('15', 'Manchester City', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('16', 'Atlético de Madrid', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('17', 'AS Mónaco', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('18', 'AFC Ajax', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('19', 'Alemania', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('20', 'Alemania (F)', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('21', 'Argentina', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('22', 'Arsenal FC', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('23', 'Athletic Club Bilbao', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('24', 'Brasil (F)', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('25', 'Brasil', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('26', 'CSKA Moskva', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('27', 'EE UU (F)', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('28', 'España (F)', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('29', 'España', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('30', 'FC Barcelona', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('31', 'Holanda', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('32', 'Italia', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('33', 'Juventus', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('34', 'Liverpool FC', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('35', 'Mönchengladbach', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('36', 'Napoli', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('37', 'Olympique Lyonnais', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('38', 'Portugal', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('39', 'PSV', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('40', 'Sevilla FC', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('41', 'Shakhtar Donetsk', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('42', 'VFL Wolfsburg', '??');
INSERT INTO equipo (id, nombre, imagen) VALUES ('43', 'Zenit', '??');