INSERT INTO usuario (id, nombre) VALUES (1, 'Miguel');
INSERT INTO usuario (id, nombre) VALUES (2, 'Javi');
INSERT INTO usuario (id, nombre) VALUES (3, 'Chechu');
INSERT INTO edicion (id, fecha, hora, mins) VALUES (1, '2018-06-03', 12, 16);
INSERT INTO partido (id, edicion, tipo, num_ed, prorroga, penaltis, ganador_penaltis) VALUES (1, 1, 'Fase de Grupos', 1, false, false, 0);
INSERT INTO marcador (partido, equipo, usuario, local, goles, ta, tr) VALUES (1, 2, 1, 1, 2, 0, 0);
INSERT INTO marcador (partido, equipo, usuario, local, goles, ta, tr) VALUES (1, 1, 2, 0, 3, 2, 0);
INSERT INTO partido (id, edicion, tipo, num_ed, prorroga, penaltis, ganador_penaltis) VALUES (2, 1, 'Fase de Grupos', 2, false, false, 0);
INSERT INTO marcador (partido, equipo, usuario, local, goles, ta, tr) VALUES (2, 3, 3, 1, 2, 0, 0);
INSERT INTO marcador (partido, equipo, usuario, local, goles, ta, tr) VALUES (2, 2, 1, 0, 2, 0, 0);
INSERT INTO partido (id, edicion, tipo, num_ed, prorroga, penaltis, ganador_penaltis) VALUES (3, 1, 'Fase de Grupos', 3, false, false, 0);
INSERT INTO marcador (partido, equipo, usuario, local, goles, ta, tr) VALUES (3, 1, 2, 1, 4, 0, 2);
INSERT INTO marcador (partido, equipo, usuario, local, goles, ta, tr) VALUES (3, 3, 3, 0, 1, 0, 0);
INSERT INTO partido (id, edicion, tipo, num_ed, prorroga, penaltis, ganador_penaltis) VALUES (4, 1, 'Final', 4, true, false, 0);
INSERT INTO marcador (partido, equipo, usuario, local, goles, ta, tr) VALUES (4, 1, 2, 1, 2, 0, 0);
INSERT INTO marcador (partido, equipo, usuario, local, goles, ta, tr) VALUES (4, 2, 1, 0, 1, 0, 0);
INSERT INTO edicion (id, fecha, hora, mins) VALUES (2, '2018-06-03', 12, 33);
INSERT INTO partido (id, edicion, tipo, num_ed, prorroga, penaltis, ganador_penaltis) VALUES (5, 2, 'Fase de Grupos', 1, false, false, 0);
INSERT INTO marcador (partido, equipo, usuario, local, goles, ta, tr) VALUES (5, 4, 1, 1, 3, 0, 0);
INSERT INTO marcador (partido, equipo, usuario, local, goles, ta, tr) VALUES (5, 2, 3, 0, 0, 0, 0);
INSERT INTO partido (id, edicion, tipo, num_ed, prorroga, penaltis, ganador_penaltis) VALUES (6, 2, 'Fase de Grupos', 2, false, false, 0);
INSERT INTO marcador (partido, equipo, usuario, local, goles, ta, tr) VALUES (6, 2, 3, 1, 0, 0, 0);
INSERT INTO marcador (partido, equipo, usuario, local, goles, ta, tr) VALUES (6, 1, 2, 0, 1, 0, 0);
INSERT INTO partido (id, edicion, tipo, num_ed, prorroga, penaltis, ganador_penaltis) VALUES (7, 2, 'Final', 3, true, true, 1);
INSERT INTO marcador (partido, equipo, usuario, local, goles, ta, tr) VALUES (7, 4, 1, 1, 0, 0, 0);
INSERT INTO marcador (partido, equipo, usuario, local, goles, ta, tr) VALUES (7, 1, 2, 0, 0, 0, 0);
INSERT INTO usuario (id, nombre) VALUES (1, 'Miguel');
INSERT INTO usuario (id, nombre) VALUES (2, 'Javi');
INSERT INTO usuario (id, nombre) VALUES (3, 'Chechu');
INSERT INTO edicion (id, fecha, hora, mins) VALUES (1, '2018-06-03', 15, 36);
INSERT INTO usuario (id, nombre) VALUES (1, 'Miguel');
INSERT INTO usuario (id, nombre) VALUES (2, 'Javi');
INSERT INTO usuario (id, nombre) VALUES (3, 'Chechu');
INSERT INTO edicion (id, fecha, hora, mins) VALUES (1, '2018-06-03', 15, 43);
INSERT INTO eleccion (edicion, usuario, equipo) VALUES (1, 1, 3);
INSERT INTO eleccion (edicion, usuario, equipo) VALUES (1, 2, 1);
INSERT INTO eleccion (edicion, usuario, equipo) VALUES (1, 3, 2);
INSERT INTO partido (id, edicion, tipo, num_ed, prorroga, penaltis, ganador_penaltis) VALUES (1, 1, 'Fase de Grupos', 1, false, false, 0);
INSERT INTO marcador (partido, edicion, equipo, usuario, local, goles, ta, tr) VALUES (1, 1, 3, 1, 1, 1, 0, 0);
INSERT INTO marcador (partido, edicion, equipo, usuario, local, goles, ta, tr) VALUES (1, 1, 1, 2, 0, 3, 0, 0);
INSERT INTO edicion (id, fecha, hora, mins) VALUES (2, '2018-06-03', 16, 12);
INSERT INTO eleccion (edicion, usuario, equipo) VALUES (2, 1, 4);
INSERT INTO eleccion (edicion, usuario, equipo) VALUES (2, 2, 1);
INSERT INTO eleccion (edicion, usuario, equipo) VALUES (2, 3, 2);
INSERT INTO partido (id, edicion, tipo, num_ed, prorroga, penaltis, ganador_penaltis) VALUES (2, 2, 'Fase de Grupos', 1, false, false, 0);
INSERT INTO marcador (partido, edicion, equipo, usuario, local, goles, ta, tr) VALUES (2, 2, 4, 1, 1, 1, 0, 0);
INSERT INTO marcador (partido, edicion, equipo, usuario, local, goles, ta, tr) VALUES (2, 2, 1, 2, 0, 4, 0, 0);
